name: Node JS CI/CD Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build_node_js:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup node env
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: install dependencies
              run: npm install 

            - name: Start Server in Background
              run: |
                nohup node index.js > server.log 2>&1 &

