name: Node JS CI/CD Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build_node_js:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup node env
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: install dependencies
              run: npm install 

            - name: Start Server 
              run: setsid npm start &

            - name: Wait for Server to Start
              run: sleep 20

            - name: check connectivity
              run: curl -Is http://localhost:5000
            
            - name: stop server
              run: pkill -f "node"



